// Generated by gopeed-file-category-icons. Do not edit by hand.
import 'package:flutter/widgets.dart';

abstract final class GopeedIcons {
  static const String _fontFamily = 'GopeedIcons';
  static const IconData protocolBt = IconData(0xe900, fontFamily: _fontFamily);
  static const IconData protocolEd2k = IconData(0xe901, fontFamily: _fontFamily);
  static const IconData folder = IconData(0xe902, fontFamily: _fontFamily);
  static const IconData folderBt = IconData(0xe903, fontFamily: _fontFamily);
  static const IconData file = IconData(0xe904, fontFamily: _fontFamily);
  static const IconData fileInstaller = IconData(0xe905, fontFamily: _fontFamily);
  static const IconData fileAndroid = IconData(0xe906, fontFamily: _fontFamily);
  static const IconData fileIos = IconData(0xe907, fontFamily: _fontFamily);
  static const IconData fileDiskImage = IconData(0xe908, fontFamily: _fontFamily);
  static const IconData fileWeb = IconData(0xe909, fontFamily: _fontFamily);
  static const IconData fileText = IconData(0xe90a, fontFamily: _fontFamily);
  static const IconData filePdf = IconData(0xe90b, fontFamily: _fontFamily);
  static const IconData fileDocument = IconData(0xe90c, fontFamily: _fontFamily);
  static const IconData fileSpreadsheet = IconData(0xe90d, fontFamily: _fontFamily);
  static const IconData filePresentation = IconData(0xe90e, fontFamily: _fontFamily);
  static const IconData fileArchive = IconData(0xe90f, fontFamily: _fontFamily);
  static const IconData fileImage = IconData(0xe910, fontFamily: _fontFamily);
  static const IconData fileAudio = IconData(0xe911, fontFamily: _fontFamily);
  static const IconData fileVideo = IconData(0xe912, fontFamily: _fontFamily);
  static const IconData fileCode = IconData(0xe913, fontFamily: _fontFamily);
  static const IconData fileEbook = IconData(0xe914, fontFamily: _fontFamily);
  static const IconData fileFont = IconData(0xe915, fontFamily: _fontFamily);
  static const IconData fileDatabase = IconData(0xe916, fontFamily: _fontFamily);
}
