name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🆕 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔧 Performance Improvements"
    labels:
      - "perf"
  - title: "🧪 Tests"
    label: "test"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📖 Document"
    label: "docs"
  - title: "🚀 CI/CD"
    label: "ci"
  - title: "🌎 Internationalization"
    label: "translation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  <table>
    <thead>
      <tr>
        <th colspan="2">Windows</th>
        <th>MacOS</th>
        <th colspan="4">Linux</th>
        <th>Android</th>
        <th>iOS</th>
        <th>Docker</th>
        <th colspan="2">Qnap</th>
        <th colspan="8">Web</th>
      </tr>
      <tr>
        <td><code>EXE</code></td>
        <td><code>Portable</code></td>
        <td><code>DMG</code></td>
        <td><code>Flathub</code></td>
        <td><code>SNAP</code></td>
        <td><code>DEB</code></td>
        <td><code>AppImage</code></td>
        <td><code>APK</code></td>
        <td><code>IPA</code></td>
        <td>-</td>
        <td colspan="2"><code>QPKG</code></td>
        <td colspan="3"><code>Windows</code></td>
        <td colspan="2"><code>MacOS</code></td>
        <td colspan="3"><code>Linux</code></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>amd64</td>
        <td>amd64</td>
        <td>-</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>amd64</td>
        <td>arm64</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>386</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>amd64</td>
        <td>386</td>
      </tr>
      <tr>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-windows-amd64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-windows-amd64-portable.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-macos.dmg">Link</a></td>
        <td><a href="https://flathub.org/apps/com.gopeed.Gopeed">Link</a></td>
        <td><a href="https://snapcraft.io/gopeed">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-linux-amd64.deb">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-linux-x86_64.AppImage">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-android.apk">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-$version-ios.ipa">Link</a></td>
        <td><a href="https://hub.docker.com/r/liwei2633/gopeed">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-$version-qnap-amd64.qpkg">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-$version-qnap-arm64.qpkg">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-windows-amd64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-windows-arm64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-windows-386.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-macos-amd64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-macos-arm64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-linux-amd64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-linux-arm64.zip">Link</a></td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-$version-linux-386.zip">Link</a></td>
      </tr>
    </tbody>
  </table>

  # Release notes

  $CHANGES

  # 更新日志

  $CHANGES
