name-template: "v$NEXT_PATCH_VERSION 游깯"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "游 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "游냍 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "游댢 Performance Improvements"
    labels:
      - "perf"
  - title: "游빍 Tests"
    label: "test"
  - title: "游빓 Maintenance"
    label: "chore"
  - title: "游닀 Document"
    label: "docs"
  - title: "游 CI/CD"
    label: "ci"
  - title: "游깵 Internationalization"
    label: "translation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  <table>
    <tbody>
      <tr>
        <td rowspan="2">游 Windows</td>
        <td><code>EXE</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-windows-amd64.zip">游닌</a></td>
      </tr>
      <tr>
        <td><code>Portable</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-windows-amd64-portable.zip">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="3">游꼝 MacOS</td>
        <td rowspan="3"><code>DMG</code></td>
        <td>universal</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-macos.dmg">游닌</a></td>
      </tr>
      <tr>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-macos-amd64.dmg">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-macos-arm64.dmg">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="6">游냖 Linux</td>
        <td><code>Flathub</code></td>
        <td>amd64</td>
        <td><a href="https://flathub.org/apps/com.gopeed.Gopeed">游닌</a></td>
      </tr>
      <tr>
        <td><code>SNAP</code></td>
        <td>amd64</td>
        <td><a href="https://snapcraft.io/gopeed">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>DEB</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-linux-amd64.deb">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-linux-arm64.deb">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>AppImage</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-linux-amd64.AppImage">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-linux-arm64.AppImage">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="4">游뱄 Android</td>
        <td rowspan="4"><code>APK</code></td>
        <td>universal</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-android.apk">游닌</a></td>
      </tr>
      <tr>
        <td>armeabi-v7a</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-android-armeabi-v7a.apk">游닌</a></td>
      </tr>
      <tr>
        <td>arm64-v8a</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-android-arm64-v8a.apk">游닌</a></td>
      </tr>
      <tr>
        <td>x86_64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-android-x86_64.apk">游닌</a></td>
      </tr>
      <tr>
        <td>游님 iOS</td>
        <td><code>IPA</code></td>
        <td>universal</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$NEXT_PATCH_VERSION-ios.ipa">游닌</a></td>
      </tr>
      <tr>
        <td>游냡 Docker</td>
        <td>-</td>
        <td>universal</td>
        <td><a href="https://hub.docker.com/r/liwei2633/gopeed">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="2">游 Qnap</td>
        <td rowspan="2"><code>QPKG</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-v$NEXT_PATCH_VERSION-qnap-amd64.qpkg">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-v$NEXT_PATCH_VERSION-qnap-arm64.qpkg">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="8">游깷 Web</td>
        <td rowspan="3"><code>Windows</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-windows-amd64.zip">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-windows-arm64.zip">游닌</a></td>
      </tr>
      <tr>
        <td>386</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-windows-386.zip">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>MacOS</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-macos-amd64.zip">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-macos-arm64.zip">游닌</a></td>
      </tr>
      <tr>
        <td rowspan="3"><code>Linux</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-linux-amd64.zip">游닌</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-linux-arm64.zip">游닌</a></td>
      </tr>
      <tr>
        <td>386</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$NEXT_PATCH_VERSION-linux-386.zip">游닌</a></td>
      </tr>
    </tbody>
  </table>

  # Release notes

  $CHANGES

  # 料얹둻了봰찅

  $CHANGES
