/// Flutter icons Gopeed
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Gopeed
///      fonts:
///       - asset: fonts/Gopeed.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Gopeed {
  Gopeed._();

  static const _kFontFam = 'Gopeed';
  static const String? _kFontPkg = null;

  static const IconData install =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_bt =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_bt =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xf0dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 =
      IconData(0xf13b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file =
      IconData(0xf15b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_alt =
      IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf =
      IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_word =
      IconData(0xf1c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_excel =
      IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_powerpoint =
      IconData(0xf1c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_image =
      IconData(0xf1c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_archive =
      IconData(0xf1c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_audio =
      IconData(0xf1c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_video =
      IconData(0xf1c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_code =
      IconData(0xf1c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_store_ios =
      IconData(0xf370, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
