
// Objective-C API for talking to the following Go packages
//
//	github.com/monkeyWie/gopeed/bind/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libgopeed_FRAMEWORK_H__
#define __Libgopeed_FRAMEWORK_H__

#include "Libgopeed.objc.h"
#include "Universe.objc.h"

#endif
