arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
preferred-supported-locales:
  - en
  - zh
untranslated-messages-file: build/l10n_untranslated.json
