display_name: Gopeed
icon: assets/icon/icon.svg
summary: A modern download manager that supports all platforms. Built with Golang and Flutter.
group: Applications/Internet
vendor: monkeyWie
packager: madoka773
packagerEmail: valigarmanda55@gmail.com
license: GPL-3.0-or-later
url: https://github.com/GopeedLab/gopeed

description: A modern download manager that supports all platforms. Built with Golang and Flutter.
keywords:
  - Application
  - DownloadManager
  - Network
  - Utility

generic_name: Download Manager

categories:
  - Network
  - Utility

startup_notify: true
